# Generated by Django 2.1.5 on 2019-06-15 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0002_auto_20190615_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beers',
            name='Created_at',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
