# Generated by Django 2.1.5 on 2019-06-15 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0003_auto_20190615_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beers_rateing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aroma', models.IntegerField()),
                ('Appearance', models.IntegerField()),
                ('Taste', models.IntegerField()),
                ('Created_User', models.CharField(max_length=255)),
                ('Created_at', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('Updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
