# Generated by Django 2.1.5 on 2019-06-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0006_auto_20190615_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='beers_rateing',
            name='Overall',
            field=models.IntegerField(default=0),
        ),
    ]
