# Generated by Django 2.1.5 on 2019-06-15 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0007_beers_rateing_overall'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(default='Default', max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('Created_at', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('Updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Beers',
            new_name='Beer',
        ),
        migrations.RenameModel(
            old_name='Beers_rateing',
            new_name='Review',
        ),
    ]
